// Mocks generated by Mockito 5.4.6 from annotations
// in freelancer/test/features/community/leaderboard_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i6;

import 'package:firebase_auth/firebase_auth.dart' as _i2;
import 'package:freelancer/core/services/auth_service.dart' as _i5;
import 'package:freelancer/core/services/leaderboard_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUserCredential_0 extends _i1.SmartFake
    implements _i2.UserCredential {
  _FakeUserCredential_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LeaderboardService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLeaderboardService extends _i1.Mock
    implements _i3.LeaderboardService {
  MockLeaderboardService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<List<Map<String, dynamic>>> getLeaderboard({int? limit = 50}) =>
      (super.noSuchMethod(
            Invocation.method(#getLeaderboard, [], {#limit: limit}),
            returnValue: _i4.Stream<List<Map<String, dynamic>>>.empty(),
          )
          as _i4.Stream<List<Map<String, dynamic>>>);

  @override
  _i4.Future<int?> getUserRank(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserRank, [userId]),
            returnValue: _i4.Future<int?>.value(),
          )
          as _i4.Future<int?>);

  @override
  _i4.Future<void> recalculatePoints(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#recalculatePoints, [userId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  List<String> getUserBadges(Map<String, dynamic>? userData) =>
      (super.noSuchMethod(
            Invocation.method(#getUserBadges, [userData]),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  _i4.Future<void> generateDemoHelpers() =>
      (super.noSuchMethod(
            Invocation.method(#generateDemoHelpers, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i5.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i4.Future<_i2.UserCredential> signInWithEmailOnly(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmailOnly, [email, password]),
            returnValue: _i4.Future<_i2.UserCredential>.value(
              _FakeUserCredential_0(
                this,
                Invocation.method(#signInWithEmailOnly, [email, password]),
              ),
            ),
          )
          as _i4.Future<_i2.UserCredential>);

  @override
  _i4.Future<_i2.UserCredential> signUpWithEmailOnly(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signUpWithEmailOnly, [email, password]),
            returnValue: _i4.Future<_i2.UserCredential>.value(
              _FakeUserCredential_0(
                this,
                Invocation.method(#signUpWithEmailOnly, [email, password]),
              ),
            ),
          )
          as _i4.Future<_i2.UserCredential>);

  @override
  _i4.Future<_i2.UserCredential?> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i4.Future<_i2.UserCredential?>.value(),
          )
          as _i4.Future<_i2.UserCredential?>);

  @override
  _i4.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
